### ISSUE TITLE
"Use only selected glyphs" not working - G3 ce, Big Sur

### ISSUE THREAD

**Issue by albertomalossi** [schriftgestalt/word-o-mat#6]
Per title, below screenshot of the report, here macro: `/Users/alberto/Library/Application Support/Glyphs 3/Scripts/vanilla/vanillaWindows.py:273: VanillaWarning: The windows `maxSize` is bigger then the initial size.`

<img width="748" alt="Screen Shot 2020-12-27 at 10 23 30" src="https://user-images.githubusercontent.com/7223757/103167692-a7bf6a80-482d-11eb-8f46-997485d76f03.png">

**Comment by schriftgestalt** [comment]
Are you sure you are using the latest version of the plugin?

**Comment by albertomalossi** [comment]
I wasn't. Thank you, closing the issue.
